spring:
  thymeleaf:
    cache: false
    suffix: .jsp
  datasource:
    url: jdbc:mysql://203.253.207.225/wikitriple?characterEncoding=utf-8
    username: wikitriple
    password: wikitriple225
    driver-class-username: com.mysql.jdbc.Driver